apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.blueGreen.activeService }}
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
    service-type: active
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "rollouts-demo.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rollout.strategy.blueGreen.previewService }}
  labels:
    {{- include "rollouts-demo.labels" . | nindent 4 }}
    service-type: preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "rollouts-demo.selectorLabels" . | nindent 4 }}